name: manual workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Selected Environment
        run: echo "Selected environment is ${{ github.event.inputs.environment }}"
