name: personal information

on:
  push:
    branches: [main]

jobs:
  details:
    runs-on: ubuntu-latest

    steps:
      - name: My name
        run: echo "Pramod Tidke"
      - name: experience
        run: echo "2 year of experience"
      - name: role is
        run: echo "software engineer"
      - name: learning
        run: echo "true"
      - name: tools
        run: echo "git, docker, kubernetes, ansible, terraform"
      - name: hobbie
        run: echo [coding, music, gaming]
