name: self hosted runner

on:
  workflow_dispatch:

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, my-linux-runner]
    steps:
      - name: Print Runner Information
        run: |
          echo "Hostname: $(hostname)"
          echo "This workflow is running on ${{ runner.os }} runner!"
          echo "Current User: $(whoami)"
