name: ubuntu runner

on:
  workflow_dispatch:

jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4

      - name: Print Runner Name
        run: |
          echo "Hostname: $(hostname)"
          echo "This workflow is running on ${{ runner.os }} runner!"
          echo "Current User: $(whoami)"

      - name: check version
        run: |
          echo "Checking versions of installed software..."
          echo "Git version: $(git --version)"
          echo "Node.js version: $(node --version)"
          echo "Python version: $(python --version)"
          echo "Java version: $(java -version 2>&1)"
          echo "Docker version: $(docker --version)"
