name: windows runner

on:
  workflow_dispatch:

jobs:
  ubuntu-runner:
    runs-on: windows-latest

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4

      - name: Print Runner Name
        run: |
          echo "Hostname: $(hostname)"
          echo "This workflow is running on ${{ runner.os }} runner!"
          echo "Current User: $(whoami)"
